# Generated by Django 5.1.3 on 2024-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_rename_age_student_age_rename_firstname_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
